[tool.poetry]
name = "fictional-tribble"
version = "0.1.0"
description = ""
authors = ["Andrew Rainboldt <arainboldt@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"
pandas = "^1.3.0"
pandas-datareader = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
